export const productsArray1 = [
  {
    name: "Кавомашина KRUPS Essential EA816570",
    img: "product-picture-id1.jpg",
    oldPrice: 22429,
    currentPrice: 12999,
    discount: 42,
    quantity: 1,
    id: 1,
  },

  {
    name: "УМБ Xiaomi Mi Power Bank 3 30000 mAh USB-C 18W Fast Charge PB3018ZM White",
    img: "product-picture-id2.jpg",
    oldPrice: 2999,
    currentPrice: 1099,
    discount: 63,
    quantity: 1,
    id: 2,
  },

  {
    name: "Набір подушок Sleepingg антиалергенних 50х70 2 шт.",
    img: "product-picture-id3.jpg",
    oldPrice: 705,
    currentPrice: 450,
    discount: 36,
    quantity: 1,
    id: 3,
  },

  {
    name: "Вуличний світильник Delux Palace A002 60W E27 Чорне золото",
    img: "product-picture-id4.jpg",
    oldPrice: 511,
    currentPrice: 457,
    discount: 10,
    quantity: 1,
    id: 4,
  },

  {
    name: "Клавіатура бездротова Akko 3098S London CS Jelly Purple RGB USB/Bluetooth Green-White",
    img: "product-picture-id5.jpg",
    oldPrice: 0,
    currentPrice: 2999,
    discount: 0,
    quantity: 1,
    id: 5,
  },
  {
    name: "Мобільний телефон Samsung Galaxy A24 6/128GB Dark Red (SM-A245FDRVSEK)",
    img: "product-picture-id6.jpg",
    oldPrice: 9999,
    currentPrice: 8999,
    discount: 11,
    quantity: 1,
    id: 6,
  },

  {
    name: "Комплект постільної білизни Zastelli Листя Y20960 Blue євро 200х220 см бязь (2100000280353)",
    img: "product-picture-id7.jpg",
    oldPrice: 1578,
    currentPrice: 985,
    discount: 38,
    quantity: 1,
    id: 7,
  },
  {
    name: "Набір підносів Supretto із бамбука для сніданку 2 шт (7898-0001)",
    img: "product-picture-id8.jpg",
    oldPrice: 0,
    currentPrice: 799,
    discount: 0,
    quantity: 1,
    id: 8,
  },
  {
    name: "Сервіз столовий Luminarc Diwali Light Turquoise 18 предметів (P2963)",
    img: "product-picture-id9.jpg",
    oldPrice: 2020,
    currentPrice: 1449,
    discount: 29,
    quantity: 1,
    id: 9,
  },
  {
    name: "Пральний порошок Persil автомат Color 5.25 кг (9000101573817)",
    img: "product-picture-id10.jpg",
    oldPrice: 785,
    currentPrice: 599,
    discount: 24,
    quantity: 1,
    id: 10,
  },
  {
    name: "Настінний годинник UTA 045 VP садові квіти в кошику",
    img: "product-picture-id11.jpg",
    oldPrice: 0,
    currentPrice: 340,
    discount: 0,
    quantity: 1,
    id: 11,
  },
  {
    name: "Чайний сервіз Lefard 15 предметів (586-322)",
    img: "product-picture-id12.jpg",
    oldPrice: 0,
    currentPrice: 5245,
    discount: 0,
    quantity: 1,
    id: 12,
  },
];

export const productsArray2 = [
  {
    name: "Кондиціонер HYUNDAI ARN09HSSUAWF1/ARU09HSSUAWF1",
    img: "product-picture-id13.jpg",
    oldPrice: 17999,
    currentPrice: 15999,
    discount: 12,
    quantity: 1,
    id: 13,
  },
  {
    name: "Контейнер для зберігання Krauff с крышкой 600 мл (29-298-026)",
    img: "product-picture-id14.jpg",
    oldPrice: 339,
    currentPrice: 170,
    discount: 50,
    quantity: 1,
    id: 14,
  },
  {
    name: "Робот-пилесос Rowenta X-PLORER S130AI Standard White RR9067WH",
    img: "product-picture-id15.jpg",
    oldPrice: 26009,
    currentPrice: 12999,
    discount: 50,
    quantity: 1,
    id: 15,
  },
  {
    name: "Ваги кухонні Sea Breeze SB-070",
    img: "product-picture-id16.jpg",
    oldPrice: 0,
    currentPrice: 165,
    discount: 0,
    quantity: 1,
    id: 16,
  },
  {
    name: "Вентилятор RZTK FT 1515B",
    img: "product-picture-id17.jpg",
    oldPrice: 495,
    currentPrice: 399,
    discount: 20,
    quantity: 1,
    id: 17,
  },
  {
    name: "Ремінець BeCover для Huawei Band 7/Honor Band 7 Black (BC_709456)",
    img: "product-picture-id18.jpg",
    oldPrice: 0,
    currentPrice: 179,
    discount: 0,
    quantity: 1,
    id: 18,
  },

  {
    name: "KIOXIA TransMemory U202 64GB USB 2.0 White (LU202W064GG4)",
    img: "product-picture-id19.jpg",
    oldPrice: 189,
    currentPrice: 129,
    discount: 32,
    quantity: 1,
    id: 19,
  },
  {
    name: "Мережевий розгалужувач Allocacoc Powercube На 5 розеток Зелений (1100GN / DEORP)",
    img: "product-picture-id20.jpg",
    oldPrice: 468,
    currentPrice: 349,
    discount: 25,
    quantity: 1,
    id: 20,
  },
  {
    name: "Рюкзак для ноутбука RivaCase 8365 17.3 Blue (8365 (Blue))",
    img: "product-picture-id21.jpg",
    oldPrice: 2249,
    currentPrice: 1599,
    discount: 29,
    quantity: 1,
    id: 21,
  },
  {
    name: "Підставка для ноутбука OfficePro LS111B Aluminium alloys Black",
    img: "product-picture-id22.jpg",
    oldPrice: 0,
    currentPrice: 1499,
    discount: 0,
    quantity: 1,
    id: 22,
  },
  {
    name: "A4Tech PK-940HA 1080P Black (4711421954648)",
    img: "product-picture-id23.jpg",
    oldPrice: 0,
    currentPrice: 1699,
    discount: 0,
    quantity: 1,
    id: 23,
  },
  {
    name: "Мікрофон HyperX QuadCast S (HMIQ1S-XX-RG/G / 4P5P7AA)",
    img: "product-picture-id24.jpg",
    oldPrice: 0,
    currentPrice: 7799,
    discount: 0,
    quantity: 1,
    id: 24,
  },
];
